#### Lecture 1. 행렬 분해

##### mini code :

In [1]:
# epsilon approximation
guess = 0.0
cube = 27
increment = 0.0001
epsilon = 0.1

while abs(guess ** 3 - cube) >= epsilon:
    guess += increment

print('{} is close enough to the cube root of {}'.format(guess, cube))

2.9963000000018987 is close enough to the cube root of 27


In [4]:
# NMF : Non-negative Matrix Factorization
import pandas as pd
import numpy as np
df = pd.DataFrame({'Doc1':[3, 2, 8, 0, 0],
                   'Doc2':[1, 4, 12, 0, 0],
                   'Doc3':[0, 0, 0, 10, 11],
                   'Doc4':[0, 0, 0, 8, 5],
                   'Doc5':[1, 1, 1, 1, 1]},
                   index = ['col0', 'col1', 'col2', 'col3', 'col4'])

from sklearn import decomposition
model = decomposition.NMF(2)
original = df.values
W = model.fit_transform(original)
H = model.components_
print('W matrix: \n', W.round(2), '\n')
print('H matrix: \n', H.round(2), '\n')

np.set_printoptions(suppress=True)
approx = np.round(np.dot(W, H), 3)
print("Approximated matrix: \n", approx, '\n')
print("Original matrix: \n", original)

W matrix: 
 [[0.01 0.66]
 [0.01 1.15]
 [0.   3.69]
 [3.05 0.  ]
 [2.87 0.  ]] 

H matrix: 
 [[0.   0.   3.54 2.21 0.34]
 [2.2  3.22 0.   0.   0.36]] 

Approximated matrix: 
 [[ 1.458  2.136  0.052  0.033  0.242]
 [ 2.528  3.705  0.04   0.025  0.415]
 [ 8.113 11.888  0.     0.     1.319]
 [ 0.003  0.    10.788  6.733  1.032]
 [ 0.003  0.001 10.164  6.344  0.972]] 

Original matrix: 
 [[ 3  1  0  0  1]
 [ 2  4  0  0  1]
 [ 8 12  0  0  1]
 [ 0  0 10  8  1]
 [ 0  0 11  5  1]]


C:\Users\jinwo\miniconda3\envs\kaggle\lib\site-packages\sklearn\decomposition\_nmf.py:315: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  "'nndsvda' in 1.1 (renaming of 0.26)."), FutureWarning)


1. maps
- Matrix(Tensor) is a data modeling tool
- Matrix(Tensor) is a linear transformation
    - 선형 변환 : 변환 후 벡터의 덧셈과 스칼라곱을 보존하는 변환
- terminology
    - filter decomposition : 필터를 나타내는 데이터의 분해 (conv. layer)
    - matrix factorization : 2차원으로 데이터 분해
    - tensor factorization : 고차원으로 데이터 분해
- Gaussian elimination
    - basis : matrix의 선형공간을 정의하는 기본단위가 되는 벡터의 set
    - basis 끼리는 linearly independent

2. kernel method
- kernel : central essential part
- filter decomposition : depth-wise separable convolution

3. matrix decomposition
- eigenvalue decompostion, SVD(singular value decomposition) $ A = U\sum V^T $
- eigenvector : 변환 후에 방향이 보존되는 벡터(크기 변화는 eigenvalue)
- SVD 는 정방행렬(n x n matrix) 가 아니라도 적용가능
- PCA는 SVD와 유사하나 정보손실과 차원 축소가 일어남

4. tensor decomposition
- CP(canonical polyadic) decomposition
- CP model / Tucker model
- Tensor Componets Analysis(TCA)
- MobileNet block은 CP convolution의 특이 케이스