#### Lecture 0. Numpy

numpy
- NUMerical PYthon
- 파이썬의 고성능 과학 계산용 패키지
- list 에 비해 빠르고 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리 지원

ndarray
- np.array 함수 사용하여 배열 생성
- dynamic typing 이 지원되지 않고 하나의 타입만 저장 가능

In [1]:
import numpy as np
test_array = np.array(['1', "4", 5.1, 7], float) # shift+tab: 함수 정의docstring

In [2]:
type(test_array)

numpy.ndarray

In [3]:
type(test_array[1]) # str을 입력값으로 줘도 float 형변환이 일어남

numpy.float64

In [4]:
test_array.dtype # single element의 data type, 각 요소의 memory 크기 결정

dtype('float64')

In [5]:
test_array.shape

(4,)

In [6]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1]

True

In [7]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]
# list 처럼 정적인 메모리 영역을 참조하는 것이 아니기 때문에

False

array Rank에 따른 개념
- rank 0 : scalar
- rank 1 : vector
- rank 2 : matrix
- rank 3 : 3-tensor
- rank n : n-tensor

In [8]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.int8).nbytes # int8 = 1byte

6

In [9]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float64).nbytes # 64 bit = 8byte

48

In [10]:
mat = [[1,2,4,6], [1,2,4,6], [1,2,4,6]]
np.array(mat, int).shape

(3, 4)

In [11]:
np.array(mat, int).ndim

2

handling shape
- reshape : Array의 shape 크기 변경, 요소 갯수 동일, size 기반으로 갯수 선정(-1)

In [12]:
test_mat = np.array([[1,2,3,4],[5,6,7,8]])
test_mat.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
test_mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

flatten() :다차원 array를 1-dim으로 변환

In [14]:
test_mat.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

indexing : 다차원 배열에서 \[0,0\] 표기법 제공

slicing : 행과 열부분을 나눠서 slicing 가능, 부분 집합 추출 시 유용

In [15]:
test_mat[0,2]

3

In [16]:
test_mat[1,2:]

array([7, 8])

In [17]:
a = np.arange(100).reshape(10, 10)
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [18]:
np.arange(0, 5, 0.4)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8])

In [19]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty(shape=(8,)) # shape 만 주어지고 비어있는 ndarray(memory 초기화 안됨)

array([0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000, 0.000e+000,
       6.285e-321, 0.000e+000, 0.000e+000])

In [22]:
np.ones_like(test_mat) # 기존 ndarray과 shape이 같은 array 반환

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.identity(n=3, dtype=np.int8) # 단위행렬

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [24]:
np.eye(3,5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
mat = np.arange(9).reshape(-1,3)
print(np.diag(mat))
np.diag(mat, k=1)

[0 4 8]


array([1, 5])

In [26]:
np.random.uniform(0,1,10).reshape(2,5) # 모수, 크기가 주어질 때 균등분포

array([[0.05794825, 0.96590499, 0.99763789, 0.8860032 , 0.49215041],
       [0.20967828, 0.05762028, 0.15953051, 0.76727922, 0.24279658]])

In [27]:
np.random.normal(0,1,10).reshape(2,5) # 모수, 크기가 주어질 때 정규분포

array([[-1.80706918,  1.48176909,  2.76340769, -0.10510189, -0.24461899],
       [ 0.3940266 , -0.23400038,  0.42249601, -1.21633297, -0.24935891]])

operation in array

In [28]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

axis - 모든 operation function을 실행할 때 기준이 되는 dimension 축

In [29]:
test_array.sum(axis=1)

array([10, 26, 42])

In [30]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [31]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [32]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [33]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [34]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [35]:
np.concatenate((a,b), axis=1)

array([[1, 2],
       [2, 3],
       [3, 4]])

Element-wise operations : array간 shape이 같을 때 일어나는 연산

In [36]:
test_array = np.arange(1,13).reshape(3,4)
test_array * test_array

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [37]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
test_a.dot(test_a.T)

array([[14, 32],
       [32, 77]])

broadcasting - shape이 다른 배열간 연산 지원

In [41]:
test_a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
test_a + [1,10,100]

array([[  2,  12, 103],
       [  5,  15, 106]])

Numpy performance
- 속도 : for loop < list comprehension < numpy
- Numpy가 c로 구현되어 성능을 확보하는 대신, dynamic typing 포기

In [43]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar*value)
    return result

iter_max = 10000
vector = list(range(iter_max))
scalar = 5
%timeit scalar_vector_product(scalar, vector) # for loop

6.51 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [44]:
%timeit [scalar*value for value in range(iter_max)] # list comprehension

4.36 ms ± 1.19 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%timeit np.arange(iter_max) * scalar # numpy

49.9 µs ± 8.77 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


comparision

In [46]:
a = np.arange(10)
a < 4 # broadcasting 적용

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [47]:
np.any(a>5), np.any(a<0)

(True, False)

In [48]:
np.all(a<10), np.all(a<8)

(True, False)

In [49]:
np.logical_and(a>1, a<6)

array([False, False,  True,  True,  True,  True, False, False, False,
       False])

In [50]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [52]:
np.logical_or(a>7, a<4)

array([ True,  True,  True,  True, False, False, False, False,  True,
        True])

In [55]:
np.where(a<3)

(array([0, 1, 2], dtype=int64),)

In [56]:
np.where(a>5)[0]

array([6, 7, 8, 9], dtype=int64)

In [58]:
np.where(a>5, 0, 1) # where(condition, TRUE, FALSE)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [59]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [60]:
np.isfinite(a)

array([ True, False, False])

In [65]:
np.argmax(a) # 최대값의 인덱스

4

In [64]:
np.argmin(a) # 최소값의 인덱스

0

In [63]:
a = np.array([1,2,5,4,14,8,2])
a.argsort() # 작은 값의 인덱스 순으로 반환

array([0, 1, 6, 3, 2, 5, 4], dtype=int64)

In [66]:
a[a>3] # boolean index : True 인 인덱스의 원소 반환 (shape 이 같아야 함)

array([ 5,  4, 14,  8])

In [68]:
a = np.array([2,4,6,8], float)
b = np.array([1,0,0,3,1,2], int) # 반드시 integer 선언
a[b] # fancy index : array를 index value로 사용(array 값이 인덱스 범위 내 있어야함)

array([4., 2., 2., 8., 4., 6.])

In [69]:
a.take(b)

array([4., 2., 2., 8., 4., 6.])

numpy data persistance (i/o)


#### Lecture 1. Vector

벡터 : 숫자를 원소로 가지는 list or array
- 수학적으로는 공간상의 한 점
- 원점으로부터 상대적 위치 표현
- 스칼라곱 : 방향은 그대로거나 반대, 크기만 변함
- 같은 shape 이면, 합,차, 성분곱 계산 가능
- 합 차 : 벡터의 상대적 위치이동
- 노름(norm) : 원점으로부터의 거리(임의의 차원 d에서 성립)
- ML 방법론에서 어떤 norm을 사용할 지 정할때 기하학적 성질에 의존
- 제 2 코사인 법칙에 의해 두 벡터 사이각 계산
- 내적(inner product) : 정사영 된 벡터의 길이

#### Lecture 2. Matrix

행렬 : (행)벡터를 원소로 가지는 2차원 배열
- n 행(row) m 열(column) 행렬 >>> n x m 행렬 (x<sub>ij</sub>)
- 전치행렬(transpose)  X <sup>T </sup> = (x<sub>ji</sub>)
- 여러 개의 벡터를 포함하므로 여러 점들을 나타냄
- 행렬의 덧셈, 뺄셈, 성분곱은 같은 모양을 가질 때 같은 인덱스 원소끼리
- 행렬 곱 : (i번째 행벡터).(j번째 열벡터) 내적을 성분으로 가지는 행렬 계산
- np.inner : (i번째 행벡터).(j번째 행벡터) 내적 XY<sup>T</sup>
- 행렬은 벡터 공간에서 사용되는 연산자, 다른 차원의 공간으로 보낼 수 있음
- 모든 선형변환은 행렬곱으로 계산할 수 있음
- 역행렬 A<sup>-1</sup> : AA<sup>-1</sup> = A<sup>-1</sup>A = I(항등행렬)
- 역행렬 조건 : 행과 열 숫자 같음, 행렬식 != 0, 미충족시 유사역행렬 A<sup>+</sup>
    - 모든 열벡터가 선형독립(n>=m)
        - A<sup>+</sup> = (A<sup>T</sup>A)<sup>-1</sup>A<sup>T</sup> 
        - A<sup>+</sup>A = I(좌측 역행렬)
        - 선형회귀 : L2-norm 최소화
    - 모든 행벡터가 선형독립(m>=n)
        - A<sup>+</sup> = A<sup>T</sup>(AA<sup>T</sup>)<sup>-1</sup>
        - AA<sup>+</sup> = I(우측 역행렬)
        - 연립방정식의 하나의 해 찾기

In [71]:
x = np.array([[1,-2,3], [7,4,0], [-2, 2,6]])
np.linalg.inv(x)

array([[ 0.13793103,  0.10344828, -0.06896552],
       [-0.24137931,  0.06896552,  0.12068966],
       [ 0.12643678,  0.01149425,  0.10344828]])

In [72]:
y = np.array([[0,1],[1,-1],[-2,1]])
np.linalg.pinv(y)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])